# Your Name or Company
title: Pr. Dr. Michel BOURGUIGNON

# Description of your website. This is used for social sharing.
description:  

# A brief blurb about yourself
content: Nullam id dolor id nibh ultricies vehicula ut id elit. Cras mattis consectetur purus sit amet fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum.

# Add your social links
social:
  - platform: google-scholar
    url: https://scholar.google.fr/citations?user=VFDxibAAAAAJ&hl=de&oi=sra
  - platform: researchgate
    url: https://www.researchgate.net/profile/Michel_Bourguignon2
  - platform: linkedin
    url: michel-bourguignon-39036157
  - platform: E-Mail
    url: xxx@xxx.xxx

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
#sharing_image: share.jpg
#google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
